title: Azure Log Analytics
order: 20
backends:
  - ala
logsources:
    process_creation:
        category: process_creation
        product: windows
        conditions:
            EventID: 4688
        rewrite:
            product: windows
            service: security
        table: SecurityEvent
fieldmappings:
    Image: NewProcessName
    ParentImage: ParentProcessName
    User:
        EventID=4688: SubjectUserName
        EventID=4624: TargetUserName 
